### ISSUE TITLE
Root README: Broken Vue and React Example Links

### ISSUE THREAD

**Issue by bestfoodalex** [ProtonProtocol/proton-link#1]
The React and Vue example links in the root README is broken. It goes to: https://github.com/protonprotocol/proton-link-demo-multipass

<img width="271" alt="Screen Shot 2021-12-21 at 1 31 44 PM" src="https://user-images.githubusercontent.com/19152732/146987177-3bc8b1ba-7e7c-44e0-9bee-ac1503a24d7d.png">

cc: @jafri

**Comment by jafri** [comment]
@bestfoodalex removed, see the examples at https://github.com/ProtonProtocol/ProtonWeb
